Resources:
  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: EventDrivenSampleCluster  
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties: 
      ImageScanningConfiguration:
        scanOnPush: true
      RepositoryName: event-driven-sample-repository
      Tags: 
        - Key: Name
          Value: event-driven-sample-repository
Outputs:
  ECRRepository:
    Value: !GetAtt ECRRepository.Arn
    Export:
      Name: ECRRepository