Description: IAM resource to push ECR
Parameters:
  GitHubOrg:
    Type: String
    Default: Taurin190
  AccountId:
    Type: String
Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub 
                  - repo:${GitHubOrg}/${RepositoryName}:*
                  - GitHubOrg: !Ref GitHubOrg
                    RepositoryName: {'Fn::ImportValue': !Sub 'ECRRepository'}
      Policies:
        - PolicyName: ECRTestPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource: '*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                  - ecr:ListImages
                  - ecr:CompleteLayerUpload
                  - ecr:BatchCheckLayerAvailability
                Resource: !Sub 
                  - arn:aws:ecr:ap-northeast-1:${AccountId}:repository/${RepositoryName}
                  - GitHubOrg: !Ref GitHubOrg
                    RepositoryName: {'Fn::ImportValue': !Sub 'ECRRepository'}
  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1