Parameters:
  EnvironmentParamater:
    Type: String
    Default: production
Resources: 
  BatchQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      # 7日間メッセージ保持
      MessageRetentionPeriod: 604800
      # workerの負荷を抑えるためにロングポーリングにする => 最大20秒
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentParamater}-sqs
  SqsQaueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: !Ref BatchQueue
        Version: '2012-10-17'
        Statement:
          - Sid: Allow-User-SendMessage
            Effect: Allow
            # テスト用なのですべてのユーザにアクセス権限を付与する
            Principal: "*"
            Action: "sqs:*"
            Resource:
              !GetAtt BatchQueue.Arn
      Queues:
        - !Ref BatchQueue
  StatusDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Event
      AttributeDefinitions:
        - AttributeName: "EventId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "EventId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  BatchQueue:
    Value: !GetAtt BatchQueue.QueueName
    Export:
      Name: BatchQueueName
  StatusDBTableArn:
    Value: !GetAtt StatusDBTable.Arn
    Export:
      Name: StatusDBTableArn
  StatusDBTable:
    Value: !Ref StatusDBTable
    Export:
      Name: StatusDBTable