Parameters:
  EnvironmentParamater:
    Type: String
    Default: production
Resources: 
  BatchQueue:
    Type: AWS::SQS::Queue
    Properties:
      DelaySeconds: 0
      MaximumMessageSize: 262144
      # 7日間メッセージ保持
      MessageRetentionPeriod: 604800
      # workerの負荷を抑えるためにロングポーリングにする => 最大20秒
      ReceiveMessageWaitTimeSeconds: 20
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentParamater}-sqs
  StatusDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Event
      AttributeDefinitions:
        - AttributeName: "EventId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "EventId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  BatchQueue:
    Value: !GetAtt BatchQueue.QueueName
    Export:
      Name: BatchQueueName