AWSTemplateFormatVersion: '2010-09-09'
Description: 'HTTP API Sample'

Resources:
  LambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |-
          import json
          import os
          import boto3
          def lambda_handler(event, context):
            queue_name = os.environ['QUEUE_NAME']
            sqs = boto3.client("sqs", endpoint_url="https://sqs.ap-northeast-1.amazonaws.com")
            try:
              queue = sqs.get_queue_by_name(QueueName=queue_name)
            except:
              print('queue not found: ' + queue_name)

            return {
              'statusCode': 200,
              'body': json.dumps('Hello from Lambda!')
            }
      Role: !GetAtt LambdaServiceRole.Arn
      Handler: index.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          QUEUE_NAME: !ImportValue BatchQueueName
    DependsOn:
      - LambdaServiceRole
  HttpApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HttpApiSample
      ProtocolType: HTTP
  HttpApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref HttpApi
      StageName: "$default"
      AutoDeploy: true
  HttpApiHelloIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !GetAtt Lambda.Arn
      PayloadFormatVersion: '2.0'
  HttpApiHelloIntegrationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/hello"
  HttpApiHelloRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /hello
      AuthorizationType: NONE
      Target: !Sub "integrations/${HttpApiHelloIntegration}"
