Parameters:
  CidrBlockParamater:
    Type: String
    Default: 10.0.0.0/16
  EnvironmentParamater:
    Type: String
    Default: production
Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 
        Ref: CidrBlockParamater
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: stack
         Value: 
           Ref: EnvironmentParamater